### PR TITLE
target sdk=25

### PR DESCRIPTION
**Pull request by seventhmoon**
Update the project setting, targeting newest SDK. Updating the plugin version for Android Studio 2.3.

Please make sure that the following boxes are checked before submitting your Pull Request, thank you!

- [x] You have signed the [Eclipse ECA](https://wiki.eclipse.org/ECA)
- [x] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [X] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [X] If this is new functionality, You have added the appropriate Unit tests.

### CODE REVIEW

**Comment by seventhmoon** [comment]
"git commit -s" with correct email

**Comment by seventhmoon** [comment]
added 

> Signed-off-by: Fung <funglam@7thmoon.com>

**Comment by jpwsutton** [comment]
Thank you for putting this fix forward, just a few things before we can accept it, however as it's just configuration, I'm happy to go ahead and make the changes myself if you would like?

- This PR needs to target the develop branch
- You must sign the eclipse ECA before we can accept it.
- .travis.yml (https://github.com/eclipse/paho.mqtt.android/blob/develop/.travis.yml) needs to be updated as well so that the ci build can use the latest android SDK.

**Comment by seventhmoon** [comment]
Sure. Thanks.

**Comment by jpwsutton** [comment]
Thanks for suggesting this, the changes have been made in commit 62c90ac

**Pull request closed without merging**
