### PR TITLE
Update to Android Studio 3.3.2

### PR DESCRIPTION
**Pull request by Tynox**
Update to Android Studio 3.3.2:
 * Fix gradle sync error of JavaDoc task
 * Update certificates in service test. And change test server uri to iot.eclipse.org

### CODE REVIEW

**Comment by Tynox** [comment]
The certificates of the local test server is outdated. I changed the test server uri to iot.eclipse.org

**Comment by hannesa2** [comment]
@jpwsutton Is there something wrong with this PR ?

**Comment by hannesa2** [comment]
@jpwsutton Is there something wrong with this PR ?

**Comment by jpwsutton** [comment]
The PR looks good to me, Sadly I've not had much free time available for the Paho project since changing jobs last year so am no longer a comitter on the project. 

@icraggs, @hannesea2 has been contributing to the android project for some time now, do you think worth making a comitter for it?

**Comment by hannesa2** [comment]
> @icraggs, @hannesa2 has been contributing to the android project for some time now, do you think worth making a comitter for it?

Better then nobody 😄

**Pull request merged**
