### PR TITLE
FIx issue #158 NPE on AlarmPingSender.stop()

### PR DESCRIPTION
**Pull request by brstgt**
Please make sure that the following boxes are checked before submitting your Pull Request, thank you!

- [ ] You have signed the [Eclipse CLA](http://www.eclipse.org/legal/CLA.php)
- [ ] All of your commits have been signed-off with the correct email address (The same one that you used to sign the CLA)
- [x] If This PR fixes an issue, that you reference the issue below. OR if this is a new issue that you are fixing straight away that you add some Description about the bug and how this will fix it.
- [ ] If this is new functionality, You have added the appropriate Unit tests.

I wont sign anything but you can either pull these few lines or create a simple commit that fixes this issue on your own. See issue #158

### CODE REVIEW

**Comment by jpwsutton** [comment]
This fix was already partially implemented in the develop branch, and I'd been meaning to add the null check, add that with the lack of ECA, so I went and made the fix myself in commit 66eea5049

**Comment by brstgt** [comment]
Thanks! Can you give an estimate when this will be available on the maven repo? Currently I forked it and compiled it on my own but a maven dependency is always nicer.

**Comment by jpwsutton** [comment]
The next develop build will upload it in the snapshot repository at about 1am GMT tomorrow I believe

**Comment by piyushgupta27** [comment]
Hey, Has this fix been released on the maven repo? The last update to the Snapshot builds (https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/) was Nov 9. Can you please let me know is there a way to get the fix without having to fork the repo?

**Comment by brstgt** [comment]
You actually dont need to fork it. You can Check it Out and use it as a
submodule in your gradle Project. But yes a Release would be better.

Am 17.12.2016 14:28 schrieb "Piyush Gupta" <notifications@github.com>:

**Comment by jpwsutton** [comment]
@piyushgupta27 We had a small problem with our snapshot builds, It's working again now and you can download the latest snapshot here: https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.android.service/1.1.1-SNAPSHOT/

**Pull request closed without merging**
