### PR TITLE
update to AndroidStudio 3 release

### PR DESCRIPTION
**Pull request by hannesa2**
Using most recent Android Studio 3 release

### CODE REVIEW

**Comment by hannesa2** [comment]
What is this ?
image

**Comment by jpwsutton** [comment]
Looks like travis failed for an unknown reason, I've re-built the PR and that looks to have passed. Thanks for the contribution!

**Comment by lmjhw055-commits** [comment]
> Using most recent Android Studio 3 release

**Comment by lmjhw055-commits** [comment]
@lmjhw055-commits

**Pull request merged**
